@[toc]

# 匈牙利算法（Hungarian Algorithm）
目标跟踪初探（DeepSORT） - 知乎
https://zhuanlan.zhihu.com/p/90835266

假设现在有3个任务，要分别分配给3个人，每个人完成各个任务所需代价矩阵（cost matrix）如下所示（这个代价可以是金钱、时间等等）：


In [1]:
import numpy as np 
from sklearn.utils.linear_assignment_ import linear_assignment
from scipy.optimize import linear_sum_assignment
 

cost_matrix = np.array([
    [15,40,45],
    [20,60,35],
    [20,40,25]
])
 
matches = linear_assignment(cost_matrix)
print('sklearn API result:\n', matches)
matches = linear_sum_assignment(cost_matrix)
print('scipy API result:\n', matches)
 

"""Outputs
sklearn API result:
 [[0 1]         对应 0 行，1列      40
  [1 0]         对应 1 行，0列      20
  [2 2]]        对应 2 行，2列      25
scipy API result:
 (array([0, 1, 2], dtype=int64), array([1, 0, 2], dtype=int64))
"""

sklearn API result:
 [[0 1]
 [1 0]
 [2 2]]
scipy API result:
 (array([0, 1, 2]), array([1, 0, 2]))


/workspace/pyEnv/nvidia-cuda10.0-cudnn7-devel-ubuntu18.04_py3.6/deep_sort_pytorch/lib/python3.6/site-packages/sklearn/utils/linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)
/workspace/pyEnv/nvidia-cuda10.0-cudnn7-devel-ubuntu18.04_py3.6/deep_sort_pytorch/lib/python3.6/site-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


'Outputs\nsklearn API result:\n [[0 1]         对应 0 行，1列      40\n  [1 0]         对应 1 行，0列      20\n  [2 2]]        对应 2 行，2列      25\nscipy API result:\n (array([0, 1, 2], dtype=int64), array([1, 0, 2], dtype=int64))\n'

In [4]:
print(cost_matrix)
row, col = linear_sum_assignment(cost_matrix)
print(row, col)

[[15 40 45]
 [20 60 35]
 [20 40 25]]
[0 1 2] [1 0 2]


In [6]:
a = [i for i in range(0,20,2)]
print(a)
for col, idx in enumerate(a):
    print(col, idx)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0 0
1 2
2 4
3 6
4 8
5 10
6 12
7 14
8 16
9 18
